name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shanakaprageeth/ubuntu24-dpdk:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt install -y libssl-dev ninja-build
        cd /root/dpdk/
        ninja -C build install
        cd -
        export FF_PATH=f-stack
        export PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib/pkgconfig
        cd f-stack/lib/
        make


    - name: Check output
      run: tree .
