name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: shanakaprageeth/ubuntu24-dpdk:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get -qq update
        apt-get -qq install -y libssl-dev ninja-build
        # using pre-built dpdk inside the container
        cp -r /root/dpdk/build dpdk/build
        cd dpdk
        ninja -C build install
    - name: Compile f-stack
      run: |
        cd lib/
        make
    - name: Check output
      run: find . -type f -name "*.so"
